bank_app/urls.py
from django .urls import path

from bank_app import views
app_name = 'bank_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('bank/', views.home, name='bank'),

]

bank_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank_app.urls')),
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credentials/urls.py
from django.urls import path

from credentials import views

app_name = 'credentials'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('inform/', views.inform, name='inform'),
    path('personal_details_form/',views.personal_details_form, name='details_form'),
    # path('ajax/load_branches/',views.load_branches,name='ajax_branch_url'),
    path('logout/', views.logout, name='logout')

]

credentials/models.py
from django.db import models
from django.urls import reverse


class Register(models.Model):
    username = models.CharField(max_length=250, default=True)
    password = models.TextField()
    conform_password = models.TextField()

    def __str__(self):
        return self.username


class Districts(models.Model):
    name = models.CharField(max_length=250)


    def __str__(self):
        return self.name



class Branch(models.Model):
    district = models.ForeignKey(Districts, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class AccountType(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name





class FromTable(models.Model):
    name = models.CharField(max_length=50,blank=False)
    date_of_birth = models.DateField(null=True,blank=False)
    age = models.PositiveIntegerField(null=True,blank=False)
    phone_number = models.CharField(max_length=20,blank=False)
    mail_id = models.EmailField(max_length=254,unique=True,blank=False)
    address = models.TextField(blank=False)
    district = models.CharField(max_length=250,blank=False,default="thrissur")
    branch = models.CharField(max_length=250,blank=False,default='chalakudy')
    account_type = models.CharField(max_length=250,blank=True)
    choices = models.ManyToManyField('CheckboxOptions', blank=True)


    def __str__(self):
        return self.name


class CheckboxOptions(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class LoggedUser(models.Model):
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=75)

    def __str__(self):
        return self.name

templates/base1.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

    <head>

        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- title of site -->
        <title>Directory Landing Page</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="{% static 'logo/favicon.png' %}"/>

        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!--linear icon css-->
		<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">

		<!--animate.css-->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">

		<!--flaticon.css-->
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">

		<!--slick.css-->
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
		<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">

        <!--bootstrap.min.css-->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- bootsnav -->
		<link rel="stylesheet" href="{% static 'css/bootsnav.css' %}" >

        <!--style.css-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

		 <!-- Include SweetAlert library -->
    	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

        <!--responsive.css-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

        <!--[if lt IE 9]>
		        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    <style>
            html,body{
            height:100%;
            padding:0;
            margin:0;

            }
.fixdiv{
		width:100%;
		}
.form1{
        width:480px;height:300px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }
.submit{text-align:center;margin-left:auto;margin-right:auto;
}
.submt{width:170px;height:40px;border-radius:10px;float:left;
}
.submt:hover{background-color:#0D7035;}

 .form1{
           width:480px;height:250px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

        }



</style>

    </head>

        <![endif]-->

		<!-- top-area Start -->
		<section class="top-area">
			<div class="header-area">
				<!-- Start Navigation -->
			    <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy"  data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">

			        <div class="container">

			            <!-- Start Header Navigation -->
			            <div class="navbar-header">
			                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
			                    <i class="fa fa-bars"></i>
			                </button>
			                <a class="navbar-brand" href="index.html">FAITH<span>BANK</span></a>

			            </div><!--/.navbar-header-->
			            <!-- End Header Navigation -->

			            <!-- Collect the nav links, forms, and other content for toggling -->
			            <div class="collapse navbar-collapse menu-ui-design" >
			                <ul class="nav navbar-nav navbar-right" >
			                    <li class="active"><a href="{% url 'bank_app:home' %}">HOME</a></li>
								   <li class="dropdown">
									<a>BRANCH</a>
								  <ul class="dropdown-menu">
									  <li><a href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Malappuram">Malapuram</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
									  <li><a href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
								  </ul></li>
			                    <li class="scroll"><a href="#footer">contact</a></li>
								{% if user.is_authenticated %}
									<li><a href="{% url 'credentials:logout' %}" class=" btn nav-item nav-link">Logout</a></li>
								{% else %}
                    			<li><a href="credentials/login" class=" btn nav-item nav-link">Login</a></li>
                    			<li><a href="credentials/register" class="nav-item nav-link">register</a></li>
								{% endif %}
			                </ul><!--/.nav -->
			            </div><!-- /.navbar-collapse -->
			        </div><!--/.container-->
			    </nav><!--/nav-->
			    <!-- End Navigation -->
			</div><!--/.header-area-->
		    <div class="clearfix"></div>

		</section><!-- /.top-area-->
		<!-- top-area End -->
        {% block content %}
        {% endblock %}

    		<!--footer start-->
		<footer id="footer"  class="footer">
			<div class="container" style="width:100%;">
				<div class="hm-footer-copyright">
					<div class="row">
						<div class="col-sm-5">
							<p>
								&copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
							</p><!--/p-->
						</div>
						<div class="col-sm-7">
							<div class="footer-social">
								<span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</div>
						</div>
					</div>

				</div><!--/.hm-footer-copyright-->
			</div><!--/.container-->

			<div id="scroll-Top">
				<div class="return-to-top">
					<i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
				</div>

			</div><!--/.scroll-Top-->

        </footer><!--/.footer-->
		<!--footer end-->

		<!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="{% static 'js/jquery.js' %}"></script>

        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

		<!--bootstrap.min.js-->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

		<!-- bootsnav js -->
		<script src="{% static 'js/bootsnav.js' %}"></script>

        <!--feather.min.js-->
        <script  src="{% static 'js/feather.min.js' %}"></script>

        <!-- counter js -->
		<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
		<script src="{% static 'js/waypoints.min.js' %}"></script>

        <!--slick.min.js-->
        <script src="{% static 'js/slick.min.js' %}"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

        <!--Custom JS-->
        <script src="{% static 'js/custom.js' %}"></script>
	<!--sweet alert-->
		<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!--		<script>-->
<!--			swal("Hello world!");-->
<!--		</script>-->

    </body>

</html>

templates/detailsform.html
{% extends 'base1.html' %}
{% block content %}
    <div class="form-group row">
        <div class="col-mb-10">
<div style="
  outline: solid 1px black;
  display: flex;
  justify-content: center;" xmlns="http://www.w3.org/1999/html">
<div style="justify-content: center;display: flex;border-style: solid;outline: solid 1px black;width:950px;height:auto; margin: auto;
  padding: 10px;">

    <form method="post" action="{% url 'credentials:details_form' %}" enctype="multipart/form-data" class="form-horizontal " id="dataform" style="padding-top:10px;" onsubmit="return submitForm(this);">
    {% csrf_token %}
        <div style="text-align:center;margin-top:25px;margin-bottom:25px;">
            <h1 style="font-family:Times New Roman;font-size:30px;">Please fill this form for further process</h1>
        </div>
  <div class="mb-12" style="padding-top:15px;padding-bottom:15px;">
    <label for="name" class="form-label">Name:</label>
    <input type="text" class="form-control" id="name" name="name" required>
  </div>
  <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label for="dob" class="form-label">Date of Birth:</label>
    <input type="date" class="form-control" id="dob" name="date_of_birth">
    <div  class="form-text">We'll never share your email with anyone else.</div>
  </div>
     <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label for="age" class="form-label">Age:</label>
    <input name="age" type="number" class="form-control" id="age" aria-describedby="emailHelp">
    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label for="phonenumber" class="form-label">Phone Number:</label>
    <input name="phone_number" type="phonenumber" class="form-control" id="phonenumber">
    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label for="mailid" class="form-label">Mail Id:</label>
    <input name="mail_id" type="email" class="form-control" id="mailid">
    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label for="address" class="form-label">Address:</label>
      <textarea name="address" rows="4" cols="50" class="form-control" id="address" aria-describedby="emailHelp"></textarea>
    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>
           <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
            <label for="district" class="form-label">District:</label>
            <select id="district" onchange="populateStates()" name="district" >
                <option value="" selected disabled>--select a country--</option>
                <option value="Thrissur">Thrissur</option>
                <option value="kozhikode">kozhikode</option>
                <option value="kozhikode">Malapuram</option>
                <option value="kozhikode">Ernakulam</option>
                <option value="kozhikode">Kottayam</option>
                <option value="kozhikode">Kollam</option>

            </select>
    <div class="form-text">We'll never share your email with anyone else.</div>
           <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
            <label for="branch" class="form-label">Branch:</label>
            <select id="branch" onchange="populateCities()" name="branch">
                <option value="" selected disabled>--select a state</option>
            </select>
    <div class="form-text">We'll never share your email with anyone else.</div>
           </div>
             <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
            <label for="acntype" class="form-label">Account Type:</label>
                 <select id="acntype" name="account_type">
                     <option value="" selected disabled>--select a city--</option>
                     {% for t in typ %}
                        <option value="{{t.id}}">{{t}}</option>
                     {% endfor %}
                 </select>

    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3" style="padding-top:15px;padding-bottom:15px;">
    <label class="form-label" >Choices:</label>&nbsp&nbsp
      {% for option in options %}
    <input type="checkbox" class="form-check-input" value="{{option.id}}" id="{{option.id}}" name="option">
    <label for="{{option.id}}" class="form-label" >{{option.name}}</label>&nbsp&nbsp
      {% endfor %}

    <div class="form-text">We'll never share your email with anyone else.</div>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
       </div>
<div >
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#dataform").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server


<!--                let html_data = '<option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>';-->
<!--                data.forEach(function (city) {-->
<!--                    html_data += `<option value="${city.id}">${city.name}</option>`-->
<!--                });-->
<!--                console.log(html_data);-->
<!--                $("#id_city").html(html_data);-->


            }
        });

    });
</script>
<script>
    var branch = {
        Thrissur:["Chalakudy","Kundhakulam","Kodungallur","Kunnakulam",],
        Kozhikode:["Vadakara","Koyilandy","Ramanattukara","Payyoli",],
        Malapuram:["Manjeri","Thirur",Kondotty",Karippur",],
        Ernakulam:["Aluva","Angamaly","Kochi","Muvattupuzha"],
        Kottayam:["Vaikom","Kaduthuruthy","Pampady","Ettumanoor",],
        Kollam:["Karunagappally","Kunnathur","Kottarakara",Punalur",]

        };
        var districtSelect = document.getElementById("district");
        var branchSelect = document.getElementById("branch");

        function populateStates(){
                 branchSelect.innerHTML='<option value="">Select A Branch</option>';
        var selecteddistrict = districtSelect.value;
        if(selecteddistrict){
            var selectedbranches = branch[selecteddistrict];
                selectedbranches.forEach(function(branch){
            var option = document.createElement("option");
            option.value = branch;
            option.text = branch;
            branchSelect.appendChild(option);
            });
        }
    }
    </script>

</form>
    <script>
        function submitForm(form){
        swal({
            title:"submitted success fully",
        text:"this form will be submitted",
        icon :"waring",
        button :true,
        dangermode:true,})
        .then((isOkay)=>{
        if(isOkay){
        form.submit();
        }
        });
        return false;
        }
    </script>
</div>
</div>

</div>
</div>
<!-- Include JavaScript to display popup message -->
{% endblock %}

templates/dropdown.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

templates/informpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inform page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .form1{

    width:480px;
    height:250px;
    margin-left:auto;
    margin-right:auto;
    margin-top:20px;
    border-radius:10px;
    border:10px;
    border:orange;
    }
.submit{text-align:center;margin-left:auto;margin-right:auto;padding-top:80px;
}
.submt{width:170px;height:40px;border-radius:10px;
}
.submt:hover{background-color:#0D7035;}
               }
    </style>
</head>
<body>
    <div style="background-color: #eff5f5;margin-top:80px;" class="container shadow form1">
        <div class="submit mt-4 ms-3 px-4">
            <h4 style="font-family:Times New Roman">You Should Add Your Details</h4>
                    <div style="margin-top:20px;">
						<a href="{% url 'credentials:details_form' %}"><button class="submt " >
							 Click To Upload
						</button></a>
						<a href="{% url 'bank_app:home' %}"><button class="submt " >
							 Not Now
						</button></a>
                    </div>
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
            body{
            background-color: #eff5f5;
            }
        .form1{
                width:480px;height:250px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

               }
.submit{text-align:center;margin-left:auto;margin-right:auto;
}
.submt{width:170px;height:40px;border-radius:10px;float:left;
}
.submt:hover{background-color:#0D7035;}

</style>
</head>
<body class="bdy">
<div class="row form">
<h1 style="text-align:center">LOGIN</h1>
<form style="background-color: #eff5f5;" class="shadow form1" action="{% url 'credentials:login' %}" method="post">
    {% csrf_token %}
        <input class="form-control mt-4" type="text" placeholder="username" name="username"><br>
    <input class="form-control" type="password" placeholder="password" name="password"><br>
    <div class="submit mt-4 ms-3 px-4">
    <input class="submt" type="submit">
        <h5 style="padding-top:10px;"><a href="{% url 'credentials:register' %}" >don't you register</a></h5>
    </div>
</form>
</div>
{% for m in messages %}
{{ m }}
{% endfor %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

templates/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
            body{
            background-color: #eff5f5;
            }
        .form1{
                width:480px;height:250px;margin-left:auto;margin-right:auto;margin-top:20px;border-radius:10px;border:10px;border:orange;

               }
.submit{text-align:center;margin-left:auto;margin-right:auto;
}
.submt{width:170px;height:40px;border-radius:10px;float:left;
}
.submt:hover{background-color:#0D7035;}

</style>
</head>
<body class="bdy">
<div class="row form">
<h1 style="text-align:center; margin-top:7px;padding-top:15px;">REGISTER</h1>
        <form class="shadow form1 " style="background-color: #eff5f5;padding-left:13px;padding-right:13px;padding-top:20px;height:350px;" action="{% url 'credentials:register' %}" method="post">
            {% csrf_token %}
            <input class="form-control mt-4"  type="text" placeholder="username" name="username"><br>
            <input class="form-control " type="password" placeholder="password" name="password"><br>
            <input class="form-control " type="password" placeholder="comform password" name="password2"><br>
            <div class="sumbit">
            <input style="margin-left:130px;margin-top:15px;" class="submt" type="submit">
            </div>

        </form>
{% for msg in messages %}
{{msg}}
{% endfor %}
    </div>

</form>
</div>
{% for m in messages %}
{{ m }}
{% endfor %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>